/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AmbassadorsRouteImport } from './routes/ambassadors'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AdminAmbassadorsRouteImport } from './routes/admin.ambassadors'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminStylistsRouteImport } from './routes/admin.stylists'
import { Route as DesignersIndexRouteImport } from './routes/designers.index'
import { Route as DesignersSlugRouteImport } from './routes/designers.$slug'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'
import { Route as StylistsIndexRouteImport } from './routes/stylists.index'
import { Route as StylistsStylistIdRouteImport } from './routes/stylists.$stylistId'
import { Route as StylistsApplyRouteImport } from './routes/stylists.apply'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbassadorsRoute = AmbassadorsRouteImport.update({
  id: '/ambassadors',
  path: '/ambassadors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminAmbassadorsRoute = AdminAmbassadorsRouteImport.update({
  id: '/admin/ambassadors',
  path: '/admin/ambassadors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/admin/applications',
  path: '/admin/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStylistsRoute = AdminStylistsRouteImport.update({
  id: '/admin/stylists',
  path: '/admin/stylists',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignersIndexRoute = DesignersIndexRouteImport.update({
  id: '/designers/',
  path: '/designers/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignersSlugRoute = DesignersSlugRouteImport.update({
  id: '/designers/$slug',
  path: '/designers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const StylistsIndexRoute = StylistsIndexRouteImport.update({
  id: '/stylists/',
  path: '/stylists/',
  getParentRoute: () => rootRouteImport,
} as any)
const StylistsStylistIdRoute = StylistsStylistIdRouteImport.update({
  id: '/stylists/$stylistId',
  path: '/stylists/$stylistId',
  getParentRoute: () => rootRouteImport,
} as any)
const StylistsApplyRoute = StylistsApplyRouteImport.update({
  id: '/stylists/apply',
  path: '/stylists/apply',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ambassadors': typeof AmbassadorsRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin/ambassadors': typeof AdminAmbassadorsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/stylists': typeof AdminStylistsRoute
  '/designers/$slug': typeof DesignersSlugRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/stylists/$stylistId': typeof StylistsStylistIdRoute
  '/stylists/apply': typeof StylistsApplyRoute
  '/designers/': typeof DesignersIndexRoute
  '/stylists/': typeof StylistsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ambassadors': typeof AmbassadorsRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin/ambassadors': typeof AdminAmbassadorsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/stylists': typeof AdminStylistsRoute
  '/designers/$slug': typeof DesignersSlugRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/stylists/$stylistId': typeof StylistsStylistIdRoute
  '/stylists/apply': typeof StylistsApplyRoute
  '/designers': typeof DesignersIndexRoute
  '/stylists': typeof StylistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ambassadors': typeof AmbassadorsRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/admin/ambassadors': typeof AdminAmbassadorsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/stylists': typeof AdminStylistsRoute
  '/designers/$slug': typeof DesignersSlugRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/stylists/$stylistId': typeof StylistsStylistIdRoute
  '/stylists/apply': typeof StylistsApplyRoute
  '/designers/': typeof DesignersIndexRoute
  '/stylists/': typeof StylistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ambassadors'
    | '/apply'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/shop'
    | '/terms'
    | '/account'
    | '/admin/ambassadors'
    | '/admin/applications'
    | '/admin/stylists'
    | '/designers/$slug'
    | '/product/$productId'
    | '/stylists/$stylistId'
    | '/stylists/apply'
    | '/designers/'
    | '/stylists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ambassadors'
    | '/apply'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/shop'
    | '/terms'
    | '/account'
    | '/admin/ambassadors'
    | '/admin/applications'
    | '/admin/stylists'
    | '/designers/$slug'
    | '/product/$productId'
    | '/stylists/$stylistId'
    | '/stylists/apply'
    | '/designers'
    | '/stylists'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ambassadors'
    | '/apply'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/shop'
    | '/terms'
    | '/_authenticated/account'
    | '/admin/ambassadors'
    | '/admin/applications'
    | '/admin/stylists'
    | '/designers/$slug'
    | '/product/$productId'
    | '/stylists/$stylistId'
    | '/stylists/apply'
    | '/designers/'
    | '/stylists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AmbassadorsRoute: typeof AmbassadorsRoute
  ApplyRoute: typeof ApplyRoute
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShopRoute: typeof ShopRoute
  TermsRoute: typeof TermsRoute
  AdminAmbassadorsRoute: typeof AdminAmbassadorsRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminStylistsRoute: typeof AdminStylistsRoute
  DesignersSlugRoute: typeof DesignersSlugRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  StylistsStylistIdRoute: typeof StylistsStylistIdRoute
  StylistsApplyRoute: typeof StylistsApplyRoute
  DesignersIndexRoute: typeof DesignersIndexRoute
  StylistsIndexRoute: typeof StylistsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambassadors': {
      id: '/ambassadors'
      path: '/ambassadors'
      fullPath: '/ambassadors'
      preLoaderRoute: typeof AmbassadorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/ambassadors': {
      id: '/admin/ambassadors'
      path: '/admin/ambassadors'
      fullPath: '/admin/ambassadors'
      preLoaderRoute: typeof AdminAmbassadorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stylists': {
      id: '/admin/stylists'
      path: '/admin/stylists'
      fullPath: '/admin/stylists'
      preLoaderRoute: typeof AdminStylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designers/': {
      id: '/designers/'
      path: '/designers'
      fullPath: '/designers/'
      preLoaderRoute: typeof DesignersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designers/$slug': {
      id: '/designers/$slug'
      path: '/designers/$slug'
      fullPath: '/designers/$slug'
      preLoaderRoute: typeof DesignersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stylists/': {
      id: '/stylists/'
      path: '/stylists'
      fullPath: '/stylists/'
      preLoaderRoute: typeof StylistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stylists/$stylistId': {
      id: '/stylists/$stylistId'
      path: '/stylists/$stylistId'
      fullPath: '/stylists/$stylistId'
      preLoaderRoute: typeof StylistsStylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stylists/apply': {
      id: '/stylists/apply'
      path: '/stylists/apply'
      fullPath: '/stylists/apply'
      preLoaderRoute: typeof StylistsApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AmbassadorsRoute: AmbassadorsRoute,
  ApplyRoute: ApplyRoute,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShopRoute: ShopRoute,
  TermsRoute: TermsRoute,
  AdminAmbassadorsRoute: AdminAmbassadorsRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminStylistsRoute: AdminStylistsRoute,
  DesignersSlugRoute: DesignersSlugRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  StylistsStylistIdRoute: StylistsStylistIdRoute,
  StylistsApplyRoute: StylistsApplyRoute,
  DesignersIndexRoute: DesignersIndexRoute,
  StylistsIndexRoute: StylistsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
